name: gazebo8_ubuntu_import
method: http://packages.osrfoundation.org/gazebo/ubuntu
suites: [xenial, yakkety, zesty]
component: main
architectures: [amd64, arm64, armhf, i386, source]
filter_formula: Package (% gazebo-dbg ) | Package (% gazebo ) | Package (% sdformat)
