name: gazebo8_debian_import
method: http://packages.osrfoundation.org/gazebo/debian-stable
suites: [stretch]
component: main
architectures: [amd64, arm64, armhf, i386, source]
filter_formula: Package (% gazebo8-dbg ) | Package (% gazebo8 ) | Package (== libsdformat5-dbg) | Package (== libsdformat5-dev) | Package (== libsdformat5) | Package (== libignition-math3) | Package (== libignition-math3-dev) | Package (== libignition-math3-dbg) | Package (== libignition-transport3) | Package (== libignition-transport3-dev) | Package (== libignition-transport3-dbg) | Package (== libignition-msgs-dev) | Package (== libignition-msgs0) | Package (== libignition-msgs0-dbg)
