name: ignition_edifice_debian_buster.yaml
method: http://packages.osrfoundation.org/gazebo/debian-stable
suites: [buster]
component: main
architectures: [amd64, source]
filter_formula: "\
(Package (% ignition-edifice), $Version (% 1.0.0*))|\
(Package (% libignition-common4), $Version (% 4.0.0*))|\
(Package (% libignition-common4-av), $Version (% 4.0.0*))|\
(Package (% libignition-common4-av-dev), $Version (% 4.0.0*))|\
(Package (% libignition-common4-core-dev), $Version (% 4.0.0*))|\
(Package (% libignition-common4-dev), $Version (% 4.0.0*))|\
(Package (% libignition-common4-events), $Version (% 4.0.0*))|\
(Package (% libignition-common4-events-dev), $Version (% 4.0.0*))|\
(Package (% libignition-common4-graphics), $Version (% 4.0.0*))|\
(Package (% libignition-common4-graphics-dev), $Version (% 4.0.0*))|\
(Package (% libignition-common4-profiler), $Version (% 4.0.0*))|\
(Package (% libignition-common4-profiler-dev), $Version (% 4.0.0*))|\
(Package (% libignition-fuel-tools6), $Version (% 6.0.0*))|\
(Package (% libignition-fuel-tools6-dev), $Version (% 6.0.0*))|\
(Package (% libignition-gazebo5), $Version (% 5.0.0*))|\
(Package (% libignition-gazebo5-dev), $Version (% 5.0.0*))|\
(Package (% libignition-gazebo5-plugins), $Version (% 5.0.0*))|\
(Package (% libignition-gui5), $Version (% 5.0.0*))|\
(Package (% libignition-gui5-dev), $Version (% 5.0.0*))|\
(Package (% libignition-launch4), $Version (% 4.0.0*))|\
(Package (% libignition-launch4-dev), $Version (% 4.0.0*))|\
(Package (% libignition-msgs7), $Version (% 7.0.0*))|\
(Package (% libignition-msgs7-dbg), $Version (% 7.0.0*))|\
(Package (% libignition-msgs7-dev), $Version (% 7.0.0*))|\
(Package (% libignition-physics4), $Version (% 4.0.0*))|\
(Package (% libignition-physics4-core-dev), $Version (% 4.0.0*))|\
(Package (% libignition-physics4-dartsim), $Version (% 4.0.0*))|\
(Package (% libignition-physics4-dartsim-dev), $Version (% 4.0.0*))|\
(Package (% libignition-physics4-dev), $Version (% 4.0.0*))|\
(Package (% libignition-physics4-mesh-dev), $Version (% 4.0.0*))|\
(Package (% libignition-physics4-sdf-dev), $Version (% 4.0.0*))|\
(Package (% libignition-physics4-tpe), $Version (% 4.0.0*))|\
(Package (% libignition-physics4-tpe-dev), $Version (% 4.0.0*))|\
(Package (% libignition-physics4-tpelib), $Version (% 4.0.0*))|\
(Package (% libignition-physics4-tpelib-dev), $Version (% 4.0.0*))|\
(Package (% libignition-rendering5), $Version (% 5.0.0*))|\
(Package (% libignition-rendering5-core-dev), $Version (% 5.0.0*))|\
(Package (% libignition-rendering5-dev), $Version (% 5.0.0*))|\
(Package (% libignition-rendering5-ogre1), $Version (% 5.0.0*))|\
(Package (% libignition-rendering5-ogre1-dev), $Version (% 5.0.0*))|\
(Package (% libignition-rendering5-ogre2), $Version (% 5.0.0*))|\
(Package (% libignition-rendering5-ogre2-dev), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-air-pressure), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-air-pressure-dev), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-altimeter), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-altimeter-dev), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-camera), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-camera-dev), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-core-dev), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-depth-camera), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-depth-camera-dev), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-dev), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-gpu-lidar), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-gpu-lidar-dev), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-imu), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-imu-dev), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-lidar), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-lidar-dev), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-logical-camera), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-logical-camera-dev), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-magnetometer), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-magnetometer-dev), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-rendering), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-rendering-dev), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-rgbd-camera), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-rgbd-camera-dev), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-thermal-camera), $Version (% 5.0.0*))|\
(Package (% libignition-sensors5-thermal-camera-dev), $Version (% 5.0.0*))|\
(Package (% libignition-transport10), $Version (% 10.0.0*))|\
(Package (% libignition-transport10-core-dev), $Version (% 10.0.0*))|\
(Package (% libignition-transport10-dbg), $Version (% 10.0.0*))|\
(Package (% libignition-transport10-dev), $Version (% 10.0.0*))|\
(Package (% libignition-transport10-log), $Version (% 10.0.0*))|\
(Package (% libignition-transport10-log-dev), $Version (% 10.0.0*))|\
(Package (% libignition-utils1), $Version (% 1.0.0*))|\
(Package (% libignition-utils1-core-dev), $Version (% 1.0.0*))|\
(Package (% libignition-utils1-dbg), $Version (% 1.0.0*))|\
(Package (% libignition-utils1-dev), $Version (% 1.0.0*))|\
(Package (% libignition-utils1-cli), $Version (% 1.0.0*))|\
(Package (% libignition-utils1-cli-dev), $Version (% 1.0.0*))|\
(Package (% libsdformat11), $Version (% 11.0.0*))|\
(Package (% libsdformat11-dbg), $Version (% 11.0.0*))|\
(Package (% libsdformat11-dev), $Version (% 11.0.0*))|\
(Package (% sdformat11-dbg), $Version (% 11.0.0*))|\
(Package (% sdformat11-doc), $Version (% 11.0.0*))|\
(Package (% sdformat11-sdf), $Version (% 11.0.0*))\
"
