name: lark-parser_stretch_buster
method: http://packages.osrfoundation.org/gazebo/debian-testing
suites: [buster, stretch]
component: main
# python packages only, all arches supported
architectures: [amd64, arm64, armhf source]
filter_formula: "\
((Package (% =lark-parser) |\
  Package (% =python3-lark-parser) |\
  Package (% =python3-lark-parser-doc)),
  $Version (% 0.7.2-3osrf~* ))\
"
