name: lark-parser_xenial_bionic
method: http://packages.osrfoundation.org/gazebo/ubuntu-testing
suites: [bionic, xenial]
component: main
# python packages only, all arches supported
architectures: [amd64, arm64, armhf source]
filter_formula: "\
((Package (% =lark-parser) |\
  Package (% =python3-lark-parser) |\
  Package (% =python3-lark-parser-doc)),
  $Version (% 0.7.2-3osrf~* ))\
"
