name: lark-parser
method: http://packages.osrfoundation.org/gazebo/debian-stable
suites: [stretch]
component: main
architectures: [amd64, arm64, source]
filter_formula: Package (% python3-lark-parser* )
# needed unless we incorporate the right gpg key
verify_release: blindtrust
