name: libopensplice69_bionic
method: http://packages.osrfoundation.org/gazebo/ubuntu-prerelease
suites: [bionic, xenial]
component: main
architectures: [amd64, arm64, armhf, source]
filter_formula: Package (= libopensplice69), $Version (% 6.9.190705+osrf1-2*)
