name: zenoh-cpp
method:  https://download.eclipse.org/zenoh/debian-repo/
suites: [/]
component: null

architectures: [amd64, arm64]
filter_formula: (Package (= libzenohcpp-dev) | Package (= libzenohc-dev) | Package (= libzenohc)), $Version (% 1.5.0)
