name: openrobotics_dart_packages_from_ppa
method: http://ppa.launchpad.net/openrobotics/dart/ubuntu/
suites: [bionic]
component: main
architectures: [amd64, armhf, arm64, i386, source]
# TODO: include version in the configuration to get a declarive way of knowing the contents of packages.osrfoundation.org
# see https://github.com/ros-infrastructure/reprepro-updater/pull/83/files
filter_formula: Package (% *dart6*), $SourceVersion(= 6.10.0~osrf20~20211005~bionic~d2b6ee08a60d0dbf71b0f008cd8fed1f611f6e24)
verify_release: blindtrust
